[tox]
envlist = py312, py313, pre-commit, docs

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
extras = docs
commands = mkdocs build --strict
